### ISSUE TITLE
pkl bug

### ISSUE THREAD

**Issue by zyxcambridge** [DanielMing123/OCCFusion#2]
![image](https://github.com/user-attachments/assets/3180ae58-837e-4e7a-a560-119a440886de)
[rank0]:     data = self.prepare_data(idx)
[rank0]:   File "/home/zyx/anaconda3/envs/OCCFusion/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 793, in prepare_data
[rank0]:     return self.pipeline(data_info)
[rank0]:   File "/home/zyx/anaconda3/envs/OCCFusion/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 60, in __call__
[rank0]:     data = t(data)
[rank0]:   File "/home/zyx/anaconda3/envs/OCCFusion/lib/python3.8/site-packages/mmcv/transforms/base.py", line 12, in __call__
[rank0]:     return self.transform(results)
[rank0]:   File "/home/zyx/code/OCCFusion/occfusion/loading.py", line 365, in transform
[rank0]:     occ_200 = np.load(occ_200_path)
[rank0]:   File "/home/zyx/anaconda3/envs/OCCFusion/lib/python3.8/site-packages/numpy/lib/npyio.py", line 405, in load
[rank0]:     fid = stack.enter_context(open(os_fspath(file), "rb"))
[rank0]: FileNotFoundError: [Errno 2] No such file or directory: 'data/nuscenes/occ_samples/n015-2018-11-21-19-21-35+0800__LIDAR_TOP__1542799322148077.pcd.bin.npy'

data/nuscenes/occ_samples
n015-2018-11-21-19-21-35+0800__LIDAR_TOP__1542799323147809.pcd.bin.npy
data/nuscenes/occ_samples
n015-2018-11-21-19-21-35+0800__LIDAR_TOP__1542799322647937.pcd.bin.npy
[rank0]:[W914 10:50:14.103421879 ProcessGroupNCCL.cpp:1168] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
E0914 10:50:15.631017 134914987575104 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 0 (pid: 59044) of binary: /home/zyx/anaconda3/envs/OCCFusion/bin/python
Traceback (most recent call last):
  File "/home/zyx/anaconda3/envs/OCCFusion/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/zyx/anaconda3/envs/OCCFusion/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/zyx/anaconda3/envs/OCCFusion/lib/python3.8/site-packages/torch/distributed/launch.py", line 208, in <module>
    main()
  File "/home/zyx/anaconda3/envs/OCCFusion/lib/python3.8/site-packages/typing_extensions.py", line 2636, in wrapper
    return arg(*args, **kwargs)
  File "/home/zyx/anaconda3/envs/OCCFusion/lib/python3.8/site-packages/torch/distributed/launch.py", line 204, in main
    launch(args)
  File "/home/zyx/anaconda3/envs/OCCFusion/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in launch
    run(args)
  File "/home/zyx/anaconda3/envs/OCCFusion/lib/python3.8/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/home/zyx/anaconda3/envs/OCCFusion/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/zyx/anaconda3/envs/OCCFusion/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/test.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-09-14_10:50:15
  host      : zyx
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 59044)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by zyxcambridge** [comment]
![image](https://github.com/user-attachments/assets/2d14bdc8-69a8-411b-8e2a-f1f97a52e6b3)

**Comment by zyxcambridge** [comment]
[rank0]: Traceback (most recent call last):
[rank0]:   File "tools/test.py", line 169, in <module>
[rank0]:     main()
[rank0]:   File "tools/test.py", line 165, in main
[rank0]:     runner.test()
[rank0]:   File "/home/zyx/anaconda3/envs/OCCFusion/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1823, in test
[rank0]:     metrics = self.test_loop.run()  # type: ignore
[rank0]:   File "/home/zyx/anaconda3/envs/OCCFusion/lib/python3.8/site-packages/mmengine/runner/loops.py", line 445, in run
[rank0]:     self.run_iter(idx, data_batch)
[rank0]:   File "/home/zyx/anaconda3/envs/OCCFusion/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/home/zyx/anaconda3/envs/OCCFusion/lib/python3.8/site-packages/mmengine/runner/loops.py", line 466, in run_iter
[rank0]:     self.runner.call_hook(
[rank0]:   File "/home/zyx/anaconda3/envs/OCCFusion/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1839, in call_hook
[rank0]:     getattr(hook, fn_name)(self, **kwargs)
[rank0]:   File "/home/zyx/anaconda3/envs/OCCFusion/lib/python3.8/site-packages/mmdet3d/engine/hooks/visualization_hook.py", line 183, in after_test_iter
[rank0]:     assert 'img_path' in data_sample or 'lidar_path' in data_sample, \
[rank0]: AssertionError: 'data_sample' must contain 'img_path' or 'lidar_path'
[rank0]:[W914 11:19:42.615598063 ProcessGroupNCCL.cpp:1168] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
E0914 11:19:43.295622 130379626559296 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 0 (pid: 81347) of binary: /home/zyx/anaconda3/envs/OCCFusion/bin/python

**Comment by DanielMing123** [comment]
Please download the surroundocc's annotation ground truth and save it as occ_samples.
