### ISSUE TITLE
Error during training

### ISSUE THREAD

**Issue by M0L4N** [DanielMing123/OCCFusion#3]
[rank0]: Traceback (most recent call last):
[rank0]:   File "tools/train.py", line 135, in <module>
[rank0]:     main()
[rank0]:   File "tools/train.py", line 131, in main
[rank0]:     runner.train()
[rank0]:   File "/home/zxt/anaconda3/envs/OCCFusion/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1777, in train
[rank0]:     model = self.train_loop.run()  # type: ignore
[rank0]:   File "/home/zxt/anaconda3/envs/OCCFusion/lib/python3.8/site-packages/mmengine/runner/loops.py", line 98, in run
[rank0]:     self.run_epoch()
[rank0]:   File "/home/zxt/anaconda3/envs/OCCFusion/lib/python3.8/site-packages/mmengine/runner/loops.py", line 115, in run_epoch
[rank0]:     self.run_iter(idx, data_batch)
[rank0]:   File "/home/zxt/anaconda3/envs/OCCFusion/lib/python3.8/site-packages/mmengine/runner/loops.py", line 131, in run_iter
[rank0]:     outputs = self.runner.model.train_step(
[rank0]:   File "/home/zxt/anaconda3/envs/OCCFusion/lib/python3.8/site-packages/mmengine/model/wrappers/distributed.py", line 121, in train_step
[rank0]:     losses = self._run_forward(data, mode='loss')
[rank0]:   File "/home/zxt/anaconda3/envs/OCCFusion/lib/python3.8/site-packages/mmengine/model/wrappers/distributed.py", line 161, in _run_forward
[rank0]:     results = self(**data, mode=mode)
[rank0]:   File "/home/zxt/anaconda3/envs/OCCFusion/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/home/zxt/anaconda3/envs/OCCFusion/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/home/zxt/anaconda3/envs/OCCFusion/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1636, in forward
[rank0]:     else self._run_ddp_forward(*inputs, **kwargs)
[rank0]:   File "/home/zxt/anaconda3/envs/OCCFusion/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1454, in _run_ddp_forward
[rank0]:     return self.module(*inputs, **kwargs)  # type: ignore[index]
[rank0]:   File "/home/zxt/anaconda3/envs/OCCFusion/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/home/zxt/anaconda3/envs/OCCFusion/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/home/zxt/anaconda3/envs/OCCFusion/lib/python3.8/site-packages/mmdet3d/models/segmentors/base.py", line 102, in forward
[rank0]:     return self.loss(inputs, data_samples)
[rank0]:   File "/home/zxt/OCCFusion/occfusion/main.py", line 144, in loss
[rank0]:     loss = dict(level0_loss = torch.nan_to_num(self.loss_fl(vox_fl_predict_lvl0,vox_fl_label_lvl0)) + \
[rank0]:   File "/home/zxt/anaconda3/envs/OCCFusion/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/home/zxt/anaconda3/envs/OCCFusion/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/home/zxt/anaconda3/envs/OCCFusion/lib/python3.8/site-packages/focal_loss/focal_loss.py", line 77, in forward
[rank0]:     assert torch.all((x >= 0.0) & (x <= 1.0)), ValueError(
[rank0]: AssertionError: The predictions values should be between 0 and 1,                 make sure to pass the values to sigmoid for binary                 classification or softmax for multi-class classification

I just changed backbone to resnet50 
could anyone help me plz

**Comment by DanielMing123** [comment]
Please change the "load_from = 'ckpt/r101_dcn_fcos3d_pretrain.pth'" into "load_from=ckpt/resnet50-0676ba61.pth" in the config file. You need to manually download resnet50-0676ba61.pth and put it into the ckpt folder.

**Comment by M0L4N** [comment]
Thank you for your reply,  but the error still occurred after I changed it. Is there any other information I can provide？

**Comment by DanielMing123** [comment]
Did you encounter this error at the very beginning of the training?

**Comment by M0L4N** [comment]
its always occur during training

**Comment by DanielMing123** [comment]
Looks like a numerical stability problem. You can try using mmdet3d's focal loss or turn off the AMP setting in the train.py

**Comment by M0L4N** [comment]
Thanks for your advice. I'll try it.

**Comment by Gu718-git** [comment]
I have also encountered the same problem. Have you resolved it?

**Comment by M0L4N** [comment]
Not yet, I changed the loss function and AMP setting, but the error still exist. 
By the way, have you tried to resume from latest.pth？

**Comment by L1NINE** [comment]
I encountered the same problem with the default config file, during epoch 2. Has anyone solved it?

**Comment by Puiching-Memory** [comment]
This is because the model output appears infinite value during training.
The default learning rate seems excessive and performance is unstable.

I recommend narrowing it down to at least 1e-5 or 1e-6.
This at least stabilizes the value. But I think more parameters need to be adjusted, and our training accuracy is still far from the article.

**Comment by DanielMing123** [comment]
Which 2D backbone have you guys trained with? Resnet50 is not being used in our work, and we have not tested it. For the Resnet101DCN with AMP setting, please set learning rate=5e-5 to launch the training.

**Comment by Puiching-Memory** [comment]
We trained according to the configuration mentioned in the documentation.
https://github.com/DanielMing123/OCCFusion/blob/main/docs/getting_started.md

I noticed there was another file. Additional OCC3D data sets are required for training.
https://github.com/DanielMing123/OCCFusion/blob/main/configs/OccFusion_occ3d.py

If this configuration is used, the accuracy will already exceed the original configuration after 1-2 rounds.
I think this configuration adds liDAR data as a fusion. Is my understanding correct?

**Comment by DanielMing123** [comment]
The Occ3D configuration file enables our model to train on the Occ3D dataset; both approaches use multi-modality as input.

**Comment by xingxinghaq** [comment]
I had the same problem. Did you solve it?
By the way,Do you know how to save and visualise test results?

**Comment by vehxianfish** [comment]
Hi, @M0L4N, @xingxinghaq  . My env is always error. Can you give me your trainning env configuration. 

My env includes
````
python=3.10
cuda==118
torch==2.20
mmdet3d==1.4.0
```
I have tried 1 months, but errors still exists.

Thanks,best wishs!

**Comment by vcilLab-Y** [comment]
> 这是因为在训练过程中，模型输出会出现无穷大的值， 默认学习率显得过大，性能不稳定。
> 
> 我建议将其缩小到至少 1e-5 或 1e-6。 这至少可以使数值稳定下来。但我认为需要调整更多参数，而且我们的训练准确率与文章中提到的还相差甚远。

How much is the final difference in results?

**Comment by vcilLab-Y** [comment]
> 你们用哪个二维骨干模型训练的？我们的工作中没有使用 Resnet50，也没有测试过它。对于使用 AMP 设置的 Resnet101DCN，请设置学习率为 5e-5 来启动训练。

In occfusion.py, the learning rate is configured as 2e-4 rather than 5e-5. Should this be modified?

**Comment by GeorgeQ-Q** [comment]
> Which 2D backbone have you guys trained with? Resnet50 is not being used in our work, and we have not tested it. For the Resnet101DCN with AMP setting, please set learning rate=5e-5 to launch the training.

May I know the other setting for your training setting. Like how much gpus and batch size etc. Thanks
